Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@Gagandeep39 
Gagandeep39
/
angular-recipe-book
1
00
 Code Pull requests 0 Actions Security Insights Settings
Attempt 30
master @Gagandeep39  c157ecb
 
Deploy to GitHub Pages
on: push
 
Deploy to GitHub Pages
This run
Workflow file
.github/workflows/main.yml
name: Deploy to GitHub Pages

on:
  push:	
    branches:	
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - name: Build
      run: |
         npm install -g @angular/cli@6
         npm install
         ng build --prod --base-href="https://gagandeep39.github.io/angular-employee-maintenance-app/"
         cd dist/angular-employee-maintenance-app
         ls
         touch 404.html
         cp index.html 404.html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist/angular-employee-maintenance-app
